import { Host_Grotesk, Noto_Sans_JP } from 'next/font/google';

import { cn } from '@/lib/utils';

import type { Metadata } from 'next';

import './globals.css';

const notoSansJp = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  preload: false,
});

const host_Grotesk = Host_Grotesk({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          `${notoSansJp.variable} ${host_Grotesk.className} antialiased font-noto-sans-jp`,
          'bg-gradient-to-r from-purple-700/60 to-blue-500/90 max-w-7xl mx-auto',
        )}
      >
        <main className="p-8 bg-slate-50/50 shadow-2xl drop-shadow-2xl">
          {children}
        </main>
      </body>
    </html>
  );
}
